### PR TITLE
Fix: Don't show Talk link when app is not enabled

### LINKED ISSUE #61: Compatibility when "Talk" is not installed
Hello Welcome hackers :D :D Thanks for this great Welcome app. This is a minor bug report about adding more compatibility for minimal installations of Nextcloud, __without__ [NextCloud Talk (named "Spreed")](https://github.com/nextcloud/spreed).

### Steps to reproduce
1. have a Nextcloud with app "Welcome" and not app "Talk" (not "Spreed")
2. set a Welcome message
3. visit Dashboard

### Expected behaviour

We should **omit** the button "Talk with...", so there is not anymore a link to `/apps/spreed/?callUser=admin` that does not lead to a broken 404 page:

Nextcloud Welcome without Contact admin - in Italian - lol

### Actual behaviour

There is the "Contact admin" but it's a broken link.

### Server configuration

**Nextcloud version:** 29.0.9

### Proposed Implementation

1. The change should only involve this backend file:

https://github.com/nextcloud/welcome/blob/main/lib/Service/FileService.php

2. As app availability check, use `$this->appManager->isEnabledForUser('spreed')` that checks if the App NextCloud Talk is installed or not. (Don't worry, yes, it changed its name, but internally it's `spreed` and not talk).

3. To use `$this->appManager` you may want to take inspiration from this example that works, with all auto-magics of dependency-injection and auto-wiring for the AppManager: https://github.com/nextcloud/server/blob/master/apps/dav/lib/Connector/Sabre/Principal.php

4. So, if the app "`spreed`" is not available, just set `$supportUserId` and `$supportUserName` to empty strings

5. Test with Spreed App, and without Spreed app 🌈 

As maintainers said: pull request welcome \o/

## Bounty

If you propose a merge request you will probably win a 100% Italian Traditional Pizza from: @valerio-bozzolan the next time you come to Milano. lol - This coupon is valid forever ✨ unsless End Of Life of Valerio. This coupon can be transferred to one friend of yours.

Update: note that a pizza in Italy costs from 6 EUR to 15, so don't trick me ordering a 35 EUR pizza since we are not going to to buy the whole Pizzeria with this coupon. lol

### PR DESCRIPTION
**Pull request by janepie**
resolves #61

### CODE REVIEW

File: lib/Service/FileService.php [hunk 1]
```diff
@@ -33,7 +34,8 @@ public function __construct(private IRootFolder $root,
 		private IConfig $config,
 		private IURLGenerator $urlGenerator,
 		private LoggerInterface $logger,
-		private IUserManager $userManager) {
+		private IUserManager $userManager,
+		private IAppManager $appManager, ) {
```
Comment (julien-nc) [inline lib/Service/FileService.php:38]:
```suggestion
		private IAppManager $appManager,
	) {
```

**Review by julien-nc — APPROVED** [review]
